# Generated by Django 2.1.7 on 2019-04-19 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabsearch', '0002_auto_20190412_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 19, 10, 15, 32, 77877)),
        ),
    ]
